### ISSUE TITLE
continuous delivery / automatic releases

### ISSUE THREAD

**Issue by ZyanKLee** [pitkley/aws-search-extension#45]
**Preface**
By using renovate, dependabot and bors this project already does a lot to easen the burden of testing and keeping the dependencies up to date. Still forming new releases may be a big hurdle, with all the tasks to pull off and the ceremony of the whole affair. 
This hurdle is higher the more time lies and the more changes happen between releases: testing is getting more complicated and effort.

**As a developer**
you want to only care about the code and features and not be bothered with doing/initiating releases or even the decision on when to release.

**As a user**
I want to have new features and updated indices on a regular basis.

**Feature request**
Using automatic releases on each merge to "main" would take away these issues. 
"semantic-release" for example allows to define which kind of release (patch, minor, major) it will do for the type of commit it will find in the commit log. So you can decide beforehand if submodule updates by renovate will trigger a patch release (or none at all) for example.
One thing to note though is: commit messages need to follow a certain schema for semantic-release being able to parse them properly to follow these rules.

**Side note**
Another possible solution have updated indices out for the user regularly is discussed in issue #16 - but this issue is mostly about automatic releases for code changes.

**Comment by ZyanKLee** [comment]
From our discussion I want to add, if automatic releases would be done, they should not automatically submit new versions to the downstream extension stores, but only upload them to the github release page.

Anyway: As I found out how to load the CI builds through the about:debugging page, this request might not be that important anymore.

**Comment by pitkley** [comment]
As discussed, automatic releases don't make sense as long as humans are involved in the review processes on the browser vendor side. Fetching of automatically updated indices is covered in #16, building a signed artifact regularly for Firefox in #5; closing.
